### ISSUE TITLE
抽奖箱坐标不能为小数

### ISSUE THREAD

**Issue by Mcayear** [SmallasWater/LuckDraw#2]
当设置抽奖箱的坐标为小数时会发生未被处理的错误

## 抽奖箱配置文件（仅坐标部分）
```
抽奖箱坐标:
- 15.5:26:-7.5:World
```

## 报错信息
```
21:35:53 [FATAL] 于 luck 执行命令 "lch reload" 时，出现了未被处理的错误：java.lang.NumberFormatException: For input string: "15.5"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)
        at java.base/java.lang.Integer.parseInt(Integer.java:786)
        at smallaswater.luckdraw.utils.Tools.getPositionByString(Tools.java:126)
        at smallaswater.luckdraw.chests.Chest.getChest(Chest.java:135)
        at smallaswater.luckdraw.LuckDraw.initChest(LuckDraw.java:214)
        at smallaswater.luckdraw.commands.admin.ReloadSubCommand.execute(ReloadSubCommand.java:32)
        at smallaswater.luckdraw.commands.LuckCommand.execute(LuckCommand.java:74)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:297)
        at cn.nukkit.Server.dispatchCommand(Server.java:1071)
        at cn.nukkit.Player.handleDataPacket(Player.java:3615)
        at com.blocklynukkit.loader.other.ProxyPlayer.handleDataPacket(ProxyPlayer.java:268)
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:154)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:94)
        at cn.nukkit.network.Network.processInterfaces(Network.java:194)
        at cn.nukkit.Server.tick(Server.java:1487)
        at cn.nukkit.Server.tickProcessor(Server.java:1266)
        at cn.nukkit.Server.start(Server.java:1226)
        at cn.nukkit.Server.<init>(Server.java:881)
        at cn.nukkit.Nukkit.main(Nukkit.java:212)

java.lang.NumberFormatException: For input string: "15.5"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at smallaswater.luckdraw.utils.Tools.getPositionByString(Tools.java:126) ~[luckdraw_v1.4.5.jar:?]
        at smallaswater.luckdraw.chests.Chest.getChest(Chest.java:135) ~[luckdraw_v1.4.5.jar:?]
        at smallaswater.luckdraw.LuckDraw.initChest(LuckDraw.java:214) ~[luckdraw_v1.4.5.jar:?]
        at smallaswater.luckdraw.commands.admin.ReloadSubCommand.execute(ReloadSubCommand.java:32) ~[luckdraw_v1.4.5.jar:?]
        at smallaswater.luckdraw.commands.LuckCommand.execute(LuckCommand.java:74) ~[luckdraw_v1.4.5.jar:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:297) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:1071) [PowerNukkitX.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3615) [PowerNukkitX.jar:?]
        at com.blocklynukkit.loader.other.ProxyPlayer.handleDataPacket(ProxyPlayer.java:268) [BlocklyNukkit-12915-beta-r16-j17.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:154) [PowerNukkitX.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:94) [PowerNukkitX.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:194) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.tick(Server.java:1487) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1266) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.start(Server.java:1226) [PowerNukkitX.jar:?]
        at cn.nukkit.Server.<init>(Server.java:881) [PowerNukkitX.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:212) [PowerNukkitX.jar:?]
```

**Comment by Mcayear** [comment]
LuckDraw v1.4.5
